- hosts: windows
  vars:
    windows_reboot_allowed: true
    windows_pending_reboot_fail: true

  roles:
    - role: windows-pending-reboot
    - role: windows-disk-status
    - role: windows_update
